baseURL = "http://hanx11.github.io/blog/public"
title = "My Learning Notebook"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
publishdir = "public"
copyright = "Code released under the Apache 2.0 license."

[author]
  name = "HanFeng"

[params]
  DateForm = "Mon, Jan 15, 2018"
  Description = "好好学习 天天向上"
  Author = "HanFeng"
  email = "hanx11@163.com"

[[params.social]]
    title = "github"
    url = "https://github.com/hanx11"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
